/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiExclamationCircleTwotone: typeof import('@twist-space/vue2-icons/ai')['AiExclamationCircleTwotone']
    AiLeftSquareFilled: typeof import('@twist-space/vue2-icons/ai')['AiLeftSquareFilled']
    AiThunderboltFilled: typeof import('@twist-space/vue2-icons/ai')['AiThunderboltFilled']
    App: typeof import('./App.vue')['default']
    IconProvider: typeof import('@twist-space/vue2-icons')['IconProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TiCat: typeof import('@twist-space/vue2-icons/ti')['TiCat']
    TiCheckCircleFilled: typeof import('@twist-space/vue2-icons/ti')['TiCheckCircleFilled']
    TiErrorTriangle: typeof import('@twist-space/vue2-icons/ti')['TiErrorTriangle']
    TiLogoAdobePhotoshop: typeof import('@twist-space/vue2-icons/ti')['TiLogoAdobePhotoshop']
    TiModeDark: typeof import('@twist-space/vue2-icons/ti')['TiModeDark']
  }
}
