/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiThunderboltFilled: typeof import('@twistify/vue3-icons/ai')['AiThunderboltFilled']
    App: typeof import('./src/App.vue')['default']
    IconProvider: typeof import('@twistify/vue3-icons')['IconProvider']
    TiModeDark: typeof import('@twistify/vue3-icons/ti')['TiModeDark']
  }
}
